try:
 print("try block")
except:
 print("exception")
